baseURL: https://example.org/
languageCode: 'en-us'
title: Historisches Hohndorf 123
theme: hugo-flex

# Enable SCSS processing
build:
  writeStats: true

# Asset configuration
module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static

params:
  footer: true
    
  width: "100rem"
  css:
    - scss/main.scss
  # js:
  #   - js/foo.js
  #   - bar.js    