baseURL: https://example.org/
languageCode: 'en-us'
title: Historisches Hohndorf 123
theme: hugo-flex

# Enable SCSS processing
build:
  writeStats: true

# Asset configuration
module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static

params:
  footer: true
  showdate: false
  google_fonts:
    - ["UnifrakturMaguntia", "400, 700"]
    - ["Roboto", "400, 700"]
  width: "80rem"
  css:
    - scss/main.scss
  # js:
  #   - js/foo.js
  #   - bar.js    

markup:
  goldmark:
    renderer:
      unsafe: true