baseURL: https://historisches-hohndorf.de/
languageCode: 'de'
title: Historisches Hohndorf
theme: hugo-flex

# Enable SCSS processing
build:
  writeStats: true

# Asset configuration
module:
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
  imports:
    - path: github.com/hugomods/pwa
    - path: github.com/Datentechnik-Warnat/hugo-geofinder

gnoreErrors: ["error-disable-taxonomy"]
disableKinds: ["taxonomy", "term", "taxonomyTerm"]

params:
  geofinder:
    maxDistance: 1000
    floatingButtonTooltip: "Suche an aktuellem Standort"
    mobileFooter: true
    mobileRouting: true

  pwa:
    caches:
      font:
        max_age: 2592000
        origins: []
        strategy: cache-first
      image:
        max_age: 2592000
        origins: []
        strategy: cache-first
      script:
        max_age: 2592000
        origins: []
        strategy: cache-first
      style:
        max_age: 2592000
        origins: []
        strategy: cache-first
    debug: true

    icon_path: images/pwa/icon.png
    icon_sizes:
    - 48
    - 64
    - 128
    - 144
    - 256
    - 512
    manifest:
      background_color: '#005a99'
      theme_color: '#005a99'

    offline_image: images/pwa/offline.png
    
    precaches:
    - url: /
    - url: /wasserschaenke/
    - url: /images/logo.png
    - url: /wasserschaenke/images/top_image.png
    - url: /wasserschaenke/images/pic_01.png
    - url: /wasserschaenke/images/pic_01_colored.jpg
    # precaches: 
    #   - "/wasserschaenke/"


  footer: true
  showdate: false

  google_fonts:
    - ["UnifrakturMaguntia", "400, 700"]
    - ["Roboto", "400, 700"]
  width: "80rem"
  css:
    - scss/main.scss
  # js:
  #   - js/foo.js
  #   - bar.js    

markup:
  goldmark:
    renderer:
      unsafe: true


outputs:
  home:
  - HTML
  - RSS
  - Offline
  - WebAppManifest      

sitemap:
  changeFreq: ""
  disable: false
  filename: sitemap.xml
  priority: -1  